### ISSUE TITLE
Long discussion about Unascribed/Fabrication

### ISSUE THREAD

**Issue by K0-RR** [SFort/MC-noplayerlabels#3]
Since you are contributing to the Fabrication I thought these small, but must-have IMO mods could be included.
**No Player Labels
Lengthy Ladders
Good Ol' Regen
Lapis Reserve** (but if possible with some configurable changes too - not limited to that one player who put the lapis inside and without "will also be available at any other enchanting table")

I also found this but I don't know what are the differences from the original mod.
![image](https://user-images.githubusercontent.com/43277609/114280867-9b0cfe00-9a3b-11eb-882f-55e22d794df0.png)

About the old regen mod - I wanted to nerf the regeneration even more (make it slower than it was). I found https://github.com/SFort/MC-oldregen/blob/master/src/main/java/sf/ssf/sfort/Regen.java and https://github.com/SFort/MC-oldregen/blob/master/src/main/java/sf/ssf/sfort/mixin/Regen.java. Seems like I could play with those values but wanted to ask you... could you do it since I would have no idea what am I doing.

**Comment by SFort** [comment]
Problem is fabrications config system can't currently support these mods
without generating an acess amount of files.

Some of them have been integrated like Eternal Eats
but in the process all configurability was lost.
i can't dictate fabrications config format and have no clue how the UI is made so this is something that has to be added by @unascribed
(might open a discussion on it if it does not yet exist)

> Easier enchanting 

the branch adds a setting which makes the enchanting table
take 30 levels for a max enchant instead of 3.
like it used to be before enchanting required lapis
(no clue why the original dev refuses to merge it)
> "old regen mod"

Most my mods are as configurable as i can make them
but i don't know javas UI code and don't use modmenu
so i don't add support for either
Which means all the configs are oldschool text files

The format being:
```
#Value
#^-Comment describing what above value does [default value]
```
so if you wish to make the regen harder all you need todo is go to
> .minecraft/config/GoodOlRegen.conf
```
110
^-Duration in ticks between saturation based regeneration [80]
2.5
^-How much exhaustion should saturation regeneration cause  [6.0]
0.5
^-How much should saturation regeneration heal  [1.0]
true
^-Should saturation regen ignore natural regeneration gamerule [false] true | false
18
^-Amount of food required for saturation based regen [20]
80
^-Duration in ticks between food based regeneration [80]
6.0
^-How much exhaustion should food regeneration cause  [6.0]
1.0
^-How much should food regeneration heal  [1.0]
18
^-Amount of food required for food based regen [18]
1600
^-Duration in ticks between player taking damage from starvation [80]
1.0
^-Amount of damage taken for starving [1.0]
true
^-Should starvation instantly kill [false] true | false
```
and the text above is what you'll find inside

**Comment by SFort** [comment]
oh and as for Lapis Reserve configurabiliy do make a issue for that there 
(easier to keep track of it that way)

**Comment by K0-RR** [comment]
Thanks for your quick response.
This config seems easy to understand, for some reason I only have these four options in this file
```
100
^-Duration in ticks between regeneration [80]
1.5
^-How much saturation should regeneration take  [1.5]
1.0
^-How much should regeneration heal  [1.0]
false
^-Ignore natural regeneration gamerule [false] true | false

```

**Comment by SFort** [comment]
I forgot to update the github release to 1.0.1
so if you downloaded it from there you got 1.0.0 which has less configs

**Comment by K0-RR** [comment]
Ah yes, I should have checked curseforge first.
Offtopic:
On Jan 16 I made a big wishlist for Fabrication which was obviously closed as requesting so many features is bad with which I agree. Seeing as Unascribed is busy with his other projects I thought of asking you if maybe you would be interested in developing some of them? I can post send you a few most useful and easy (I think).
Example: Instant Creative Stop - Disable the player's drifting after they stopped flying in creative mode.

**Comment by SFort** [comment]
> Ah yes, I should have checked curseforge first.

frakly good you didn't tht way github has the updated version
... wierd it didn't, usually i release em first there
> Wishlist

eeeh.. tbh the reason wishlists are bad is github is bad at organizing them
and then when you actually have the time/will to do something you spend half of it deciding what searching through all the suggestions each time
and frankly at least for fabrication i think this problem is even worse when using discussions
I like the idea of instant creative stop but this is something that needs to be worked out with unascribed.

maybe try thinking of a suggestion on how to mannage all these suggestions
(aaalso i don't wanna keep a personal fabrication todo list, so please don't)

**Comment by K0-RR** [comment]
Okay.

>how to mannage all these suggestions

I'm not sure if this is what you were asking but https://trello.com/ (https://wekan.github.io/ and https://restya.com/board are open source) seems good for this. But wait isn't this the same as https://github.com/unascribed/Fabrication/projects/1?

**Comment by exaskye** [comment]
> Problem is fabrications config system can't currently support these mods without generating an acess amount of files. 

Kind of. I'd like to revamp it to add a "options.ini" alongside "features.ini", and it wouldn't be that difficult. I've been lowkey avoiding working on Fabrication lately though..

> and have no clue how the UI is made

And this is the problem I currently have with an options.ini; currently, only features.ini can be configured in the GUI. Ideally, I'd like all the INIs to be modifiable in the GUI. That's a load of work, though.

> Unascribed is busy with his other projects

Her.

> Instant Creative Stop - Disable the player's drifting after they stopped flying in creative mode.

This is kind of present in Not Enough Creativity, another one of my mods that has a total Creative mode overhaul. It has a "Free Flight" option that gives you Classic-style cheat flight with no momentum. A simpler version that just makes existing creative flight momentumless would be in-scope for Fabrication and not too difficult.

**Comment by SFort** [comment]
I'm not a fan of the way features are handled in discussions as they're very hard to browse
any chance to get em into Projects
or changing them back to issues that can be put into projects and then automaticly closing them to avoid the reason they ware moved in the first place?

**Comment by exaskye** [comment]
Yeah, the Discussions system sucks. It was the only idea I had to separate them out to keep bugs and features separate so my head didn't explode.

Maybe I should make another GitHub project and use that one's issues for features...

**Comment by SFort** [comment]
Can you add issues to Projects depending on their template / tags?

**Comment by SFort** [comment]
because if you can i thinkk the second option is best
- Add feature request template
- auto add the issue to a section in Features project called "Pending" or something
- close the issue using ISSUE_TEMPLATE or actions, so it doesn't show up on open issues

It's a bit hacky and would probably generate a lot of closed issues but i think it can work

Tried this turn out it's a pain to setup and requires way too many repo permissions

**Comment by SFort** [comment]
Also it's a shame you can't transfer issues cross user
because the majority of this thing Really belongs on the fabrication repo

**Comment by SFort** [comment]
I hope that what i'm about todo doesn't cause notification spam, but i think the discussion suggestions need to be moved
